name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pip
  - scikit-learn
  - scipy
  - pip:
      - azureml-defaults
      - inference-schema[numpy-support]
      - joblib
